import { DYNAMIC_DECIMAL } from "../helpers";

const MONGODB_USERNAME = process.env.MONGO_INITDB_ROOT_USERNAME;
const MONGODB_PASSWORD = process.env.MONGO_INITDB_ROOT_PASSWORD;
const MONGODB_DATABASE = process.env.MONGO_INITDB_ROOT_DATABASE;
const MONGODB_PORT = process.env.ME_CONFIG_MONGODB_PORT;
const MONGODB_HOST = process.env.ME_CONFIG_MONGODB_HOST;
const MONGODB_URL = `mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}`;

// General
const INITIAL_MARKET_CAP = 1e7;
const INITIAL_SUPPLY = 10e9;
const MAX_SUPPLY = 50e9;
const VALIDATING_REWARD = 5;
const TRANSACTION_FEE_PERCENTAGE = 0.01;


// Bitnomia
const BITNOMIA_LOCAL_HOST = process.env.BITNOMIA_LOCAL_HOST;

const WALLET_PUBLIC_KEY = process.env.WALLET_PUBLIC_KEY;
const WALLET_PRIVATE_KEY = process.env.WALLET_PRIVATE_KEY;

const BITNOMIA_WALLET_PUBLIC_KEY = process.env.BITNOMIA_WALLET_PUBLIC_KEY;
const BITNOMIA_WALLET_PRIVATE_KEY = process.env.BITNOMIA_WALLET_PRIVATE_KEY;

const STAKE_WALLET_PRIVATE_KEY = process.env.STAKE_WALLET_PRIVATE_KEY;
const STAKE_WALLET_PUBLIC_KEY = process.env.STAKE_WALLET_PUBLIC_KEY;

const LOST_WALLET_PUBLIC_KEY = process.env.LOST_WALLET_PUBLIC_KEY;
const LOST_WALLET_PRIVATE_KEY = process.env.LOST_WALLET_PRIVATE_KEY;


const GENESIS_WALLETS = [
    {
        public_key: BITNOMIA_WALLET_PUBLIC_KEY,
        private_key: BITNOMIA_WALLET_PRIVATE_KEY,
        balance: DYNAMIC_DECIMAL(INITIAL_SUPPLY)
    },
    {
        public_key: STAKE_WALLET_PUBLIC_KEY,
        private_key: STAKE_WALLET_PRIVATE_KEY,
        balance: 0
    },
    {
        public_key: LOST_WALLET_PUBLIC_KEY,
        private_key: LOST_WALLET_PRIVATE_KEY,
        balance: 0
    },
    {
        public_key: WALLET_PUBLIC_KEY,
        private_key: WALLET_PRIVATE_KEY,
        balance: 0
    }
]

export {
    MONGODB_URL,
    INITIAL_MARKET_CAP,
    INITIAL_SUPPLY,
    MAX_SUPPLY,
    VALIDATING_REWARD,
    TRANSACTION_FEE_PERCENTAGE,
    BITNOMIA_LOCAL_HOST,
    BITNOMIA_WALLET_PUBLIC_KEY,
    BITNOMIA_WALLET_PRIVATE_KEY,
    STAKE_WALLET_PRIVATE_KEY,
    STAKE_WALLET_PUBLIC_KEY,
    LOST_WALLET_PUBLIC_KEY,
    LOST_WALLET_PRIVATE_KEY,
    WALLET_PUBLIC_KEY,
    WALLET_PRIVATE_KEY,
    MONGODB_DATABASE,
    MONGODB_PORT,
    MONGODB_HOST,
    GENESIS_WALLETS
}