version: '3.4'

services:
  bitnomia:
    image: bitnomia
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
      
    ports:
      - 3000:3000

  # MongoDB
  mongo:
    image: mongo
    ports:
      - 27017:27017
    env_file:
      - .env
      
