apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/vultr-loadbalancer-protocol: "http"
  name: vultr-lb-http
spec:
  type: LoadBalancer
  selector:
    app: bitnomia-deployment
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP