apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitnomia-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bitnomia-deployment
  template:
    metadata:
      labels:
        app: bitnomia-deployment
    spec:
      containers:
      - name: bitnomia-deployment
        image: docker.io/brayhandeaza/bitnomia:latest
        ports:
        - containerPort: 3000
